/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    B24App: typeof import('./node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/App.vue')['default']
    B24Button: typeof import('./node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Button.vue')['default']
    B24Card: typeof import('./node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Card.vue')['default']
    B24Switch: typeof import('./node_modules/@bitrix24/b24ui-nuxt/dist/runtime/components/Switch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
